name: CI
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Get current branch
        id: branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.azure_creds }}
      - name: Pull DVC
        id: pull_dvc
        run: |
          sudo apt-get install -y python3-gi python3-gi-cairo gir1.2-secret-1 pkg-config libcairo2-dev libjpeg-dev libgif-dev libgirepository1.0-dev
          sudo snap install dvc-azure --classic
          dvc pull -v
      - name: Build images
        id: build_images
        run: |
          export DOCKER_USER=${{ secrets.DOCKERHUB_USER }}
          export DOCKER_TAG=${{ steps.branch.outputs.branch }}
          export DOCKER_TAG=${DOCKER_TAG//\//-}
          export COMPOSE_DOCKER_CLI_BUILD=1
          export DOCKER_BUILDKIT=1
          docker build . -t $DOCKER_USER/common:$DOCKER_TAG --cache-from $DOCKER_USER/common:$DOCKER_TAG
          docker-compose build
      - name: Run tests
        id: run_tests
        run: |
          export DOCKER_USER=${{ secrets.DOCKERHUB_USER }}
          export DOCKER_TAG=${{ steps.branch.outputs.branch }}
          export DOCKER_TAG=${DOCKER_TAG//\//-}
          mv secrets/arango.env.example secrets/arango.env
          docker-compose up -d arangodb
          sleep 15
          docker-compose up --exit-code-from tests tests
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Push images
        id: push_images
        run: |
          export DOCKER_USER=${{ secrets.DOCKERHUB_USER }}
          export DOCKER_TAG=${{ steps.branch.outputs.branch }}
          export DOCKER_TAG=${DOCKER_TAG//\//-}
          docker-compose push
